module.exports = {
    INVALID_BLOCK: "INVALID_BLOCK",
    BLOCK_NOT_FOUND: "BLOCK_NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID: "INVALID",
    VALIDATION_NOT_FOUND: "VALIDATION_NOT_FOUND"
};